### ISSUE TITLE
Betaflight GPLv3 licensing violation

### ISSUE THREAD

**Issue by etracer65** [aat-sentinel/FC-Betaflight#2]
It's come to our attention that this repository is distributing Betaflight firmware binaries without complying with the GPLv3 license terms. Please make the modified Betaflight source code for each pre-compiled binary hosted in this repository available for download.

The same would apply to iNav as it's also a GPLv3 licensed project.

**Comment by ShikOfTheRa** [comment]
Sure - this is no problem. Actually a PR will be submitted this week. I'd rather not keep hosting them tbh..

**Comment by etracer65** [comment]
PR will be submitted where? If the intent is to merge this into Betaflight then I think the chances are unlikely as it's outside the project scope. But with no visibility into the code changes it's difficult to say for certain.

**Comment by ShikOfTheRa** [comment]
Why would that be? iNav team accepted code OK?

Here is link to public source. I'm just looking at uploading the files direct. Did not appreciate quite how big they are
https://github.com/ShikOfTheRa/betaflight/tree/Sentinel-antenna-tracker-support
